version: "3.8"
services:
  config-server:
    image: config-server:latest
    restart: unless-stopped
    ports:
      - "8083:8083"

  classes-service:
    image: classes-service:latest
    depends_on:
      - mongodb
    ports:
      - "8082:8082"
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  welcome-service:
    image: welcome-service:latest
    ports:
      - "8110:8110"

  memberdb:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: memberdb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=memberdb
    ports:
      - "3308:3306"
    restart: unless-stopped
    volumes:
      - data:/data
  
  member-service:
    image: member-service:latest
    depends_on:
      - memberdb
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://memberdb:3306/memberdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root    

  email-service:
    image: email-service:latest
    ports:
      - "8100:8100"    

volumes:
  data: {}

networks:
  default:
    name: health_app_network