version: "3.8"
services:
  naming-server:
    image: naming-server:latest
    ports:
      - "8761:8761"
    healthcheck:
      test: curl -f http://naming-server:8761/actuator/health

  config-server:
    image: config-server:latest
    restart: unless-stopped
    healthcheck:
      test: curl -f http://config-server:8083/actuator/health
    ports:
      - "8083:8083"
    depends_on:
      - mongodb 

  classes-service:
    image: classes-service:latest
    depends_on:
      - mongodb
    ports:
      - "8082:8082"
    environment:
      EUREKA_INSTANCE_HOSTNAME: naming-server
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka 
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: rootuser
      SPRING_DATA_MONGODB_PASSWORD: rootpass
      SPRING_DATA_MONGODB_DATABASE: classinfodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_HOST: mongodb 
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  welcome-service:
    image: welcome-service:latest
    ports:
      - "8110:8110"
    environment:
      EUREKA_INSTANCE_HOSTNAME: naming-server
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka   

  memberdb:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: memberdb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=memberdb
    ports:
      - "3308:3306"
    restart: unless-stopped
    healthcheck:
      test: curl -f http://memberdb:3306/actuator/health
    volumes:
      - data:/data
  
  member-service:
    image: member-service:latest
    depends_on:
      config-server:
        condition: service_healthy
      memberdb:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://memberdb:3306/memberdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_DATABASEPLATFORM: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_DATASOURCE_USERNAME: root    
      EUREKA_INSTANCE_HOSTNAME: naming-server
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka   


  email-service:
    image: email-service:latest
    restart: unless-stopped
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "8100:8100"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8083  
      EUREKA_INSTANCE_HOSTNAME: naming-server
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka

  api-gateway:
    image: api-gateway:latest
    depends_on:
      naming-server:
        condition: service_healthy
    ports:
      - "8765:8765"
    environment:
      EUREKA_INSTANCE_HOSTNAME: naming-server
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka         

volumes:
  data: {}

networks:
  default:
    name: health_app_network