
version: "3"
services:
  membermysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=memberdb
    ports:
      - "3308:3308"
    volumes:
      - data:/data
volumes:
  data: {}




